app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.persons, name='persons'),
    path('sign_in', views.sign_in, name='sign_in'),
    path('sign_out', views.sign_out, name='sign_out'),
    path('persons/add', views.add_edit_person, name='persons_add'),
    path('persons/<int:person_id>/', views.person, name='person'),
    path('persons/<int:person_id>/edit/', views.add_edit_person, name='person_edit'),
    path('persons/<int:person_id>/delete/', views.delete_person, name='person_delete'),
    path('persons/<int:person_id>/update-status/', views.update_status, name='person_update_status'),
]

preside/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from django.utils import timezone

DEFAULT_PROFILE_PICTURE_URL = 'https://s3-us-west-2.amazonaws.com/myroadmap.io/images/profiles/nobody.jpg'

# date_created = models.DateField(default=timezone.now)

class Organization(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Person(models.Model):
    RED = '1'
    YELLOW = '2'
    GREEN = '3'
    UNKNOWN = '4'
    M = 'MALE'
    F = 'FEMALE'

    STATUS_OPTIONS = (
        (RED, 'Red'),
        (YELLOW, 'Yellow'),
        (GREEN, 'Green'),
        (UNKNOWN, 'Unknown'),
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    apartment = models.IntegerField(blank=True, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=20,
        choices=STATUS_OPTIONS,
        default=UNKNOWN,
    )
    gender = models.CharField(
        max_length=20,
        choices=((M, 'Male'), (F, 'Female')),
        default=None
    )
    calling = models.CharField(max_length=255, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    photo_url = models.CharField(max_length=255, default=DEFAULT_PROFILE_PICTURE_URL)

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"


class User(AbstractUser):
    """ This comes from the AbstractUser class
    id
    password
    last_login
    is_superuser
    username
    first_name
    last_name
    email
    is_staff
    is_active
    date_joined
    """

    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def __str__(self):
        return self.get_full_name()

class Meeting(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, default=None, null=True)
    person = models.ForeignKey(Person, related_name="meetings", on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    confidential = models.BooleanField(default=True)
    notes = models.TextField()

app/templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"/>
    <meta name="viewport" content="width=device-width"/>

    <title>{% if title %}{% block title %}{% endblock %} | {% endif %}Preside</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-black">
        <div class="container">
            <a class="navbar-brand" href="#">Preside</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if request.user.is_authenticated %}
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'persons' %}">People</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <div class="dropdown">
                        <span class="dropdown-toggle nav-link" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{request.user.get_full_name}}
                        </span>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'sign_out' %}">Log out</a>
                        </div> 
                    </div>
                </ul>
            </div>
            {% endif %}
        </div>
    </nav>

    <div class="wrapper">
        <div class="main-panel main-panel-big">
            <div class="container py-4">
                {% block body %}
                    <div class="content">
                        {% block content %}{% endblock content %}
                    </div>
                {% endblock body %}
            </div>
        </div>
    </div>
</body>

{% block footer %}
    <div class="footer container d-flex justify-content-center" style="color: rgba(255,255,255,0.4);">
        <span>&copy; {% now "Y" %} Preside</span>
    </div>
{% endblock footer %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/sweetalert2/6.0.0/sweetalert2.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.0.0/sweetalert2.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/animatecss/3.5.2/animate.min.css">

{% comment %} <script src="{% static 'app/js/main.js' %}"></script> {% endcomment %}

<script>
</script>

</html>

app/templates/person.html
{% extends "base.html" %}

{% block content %}

<a class="white" href="{% url 'persons' %} "><i class="fa fa-chevron-left"></i> Back</a>

<div class="card person-detail-card mt-5">
    <div class="card-body">
        <div class="position-absolute d-flex justify-content-end person-actions">
            <a href="{% url 'person_edit' person.id %}"><i class="fas fa-user-edit mx-2"></i></a>
            <a href="{% url 'person_delete' person.id %}"><i class="fas fa-trash-alt"></i></a>
        </div>
        <div class="student-card-header">
            <img class="person-image" src={{person.photo_url}} alt="">
            <div class="person-info ml-4">
                <div class="bold-header person-detail-name">{{ person.get_full_name }}</div>
                <p class="person-notes">{{person.notes}}</p>
            </div>
        </div>
        
        <div class="mt-3 label">Set status:</div>
        
        <nav class="nav nav-pills nav-justified">
            {% for k,v in status_options %}
                <a class="nav-item nav-link {% if k == person.status %}active status-{{k}}{% endif %}" href="{% url 'person_update_status' person.id %}?s={{k}}">{{v}}</a>
            {% endfor %}
        </nav>

        <div class="d-flex justify-content-between mb-2 mt-4 align-items-end">
            <div class="label">Meetings</div>
            <div class="btn btn-outline-primary" data-toggle="modal" data-target="#meetingModal"><i class="fa fa-plus mr-2"></i> New meeting</div>
        </div>
        <div class="meetings-container">
            {% for meeting in meetings %}
                <div class="meeting">
                    <div class="meeting-header">
                        <div>
                            <span class="label">{{meeting.date}}</span>
                            {% if meeting.confidential and request.user != meeting.user %}
                            <span class="label"> - (met with {{meeting.user.get_full_name}})</span>
                            {% endif %}
                            <div></div>
                        </div>
                        {% if meeting.confidential and request.user != meeting.user %}
                            <div class="label">Confidential<i class="fa fa-lock ml-1"></i></div>                     
                        {% endif %}
                    </div>
                    
                    {% if not meeting.confidential or request.user == meeting.user %}
                        <div class="notes-text mt-1">{{meeting.notes}}</div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="meetingModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <form method="post" autocomplete="off">
            {% csrf_token %}
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Meeting with {{person.first_name}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{meeting_form.as_p}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(document).ready(()=>{
        console.log($( "#id_date" ));
        $( "#id_date" ).datepicker();
    })
</script>

{% endblock content %}

app/templates/person_add_edit.html
{% extends "base.html" %}

{% block content %}

<div class="card slim-card">
    <form method="post">
        <div class="card-header">{% if person %}Edit{% else %}Add{% endif %} Person</div>
        <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{% if person %}
                {% url 'person' person.id %}
            {% else %}
                {% url 'persons' %}
            {% endif %}" class="btn btn-danger">Cancel</a>
        </div>
    </form>
</div>


{% endblock content %}

app/templates/persons.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">People in <span class="org-name">{{request.user.organization}}</span></div>

<div class="d-flex toolbar">
    <a class="btn btn-primary" href="{% url 'persons_add' %}"><i class="fa fa-user-plus mr-2"></i> Add Person</a>

    <form action="">
        <div class="dropdown sort-dropdown">
            <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sort By: <span class="current-selection-label">{{ current_sort_name }}</span>
            </div>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for k,v in sort_by_options.items %}
                    <a class="dropdown-item {% if current_sort_name == v %}selected{% endif %}" href="?sort_by={{ k }}">{{ v }}{% if current_sort_name == v %}<i class="fas fa-check"></i>{% endif %}</a>
                {% endfor %}
            </div>
        </div>  
    </form>
</div>


<div class="card-container mt-5">
    {% for person in persons %}
        <div class="card person-card">
                    <a class="card-link" href="{% url 'person' person.id %}">
            <div class="card-body">
                <div class="student-card-header">
                        <img class="person-image" src={{person.photo_url}} alt="">
                    <div class="name d-flex align-items-center">
                        <div class="status-dot status-{{ person.status }} mr-2"></div>
                        {{person.get_full_name}}
                    </div>
                </div>
                <div>Apartment: {{person.apartment}}</div>
                <div>Calling: {% if person.calling %}{{person.calling}}{% else %}None{% endif %}</div>
            </div>
            <div class="card-footer d-flex justify-content-between align-items-center">
                <span class="label">Last Meeting:</span><span>{{ person.meetings.first.date }}</span> 
            </div>
                    </a>
        </div>
    {% endfor %}
</div>

{% endblock content %}

app/templates/sign_in.html
{% extends "base.html" %}

{% block content %}
<div class="card slim-card">
    <div class="card-header">Sign in</div>
    <div class="card-body">
        <form id="sign-in-form" method="post" action="{% url 'sign_in' %}">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary" type="submit">Log in</button>
        </form>

        <p class="mt-5">
            <strong>**Grader Note:</strong>
            This app is intended to give leaders (especially YSA bishops), a better way to keep their people from falling through
            the cracks. It provides a bird's eye view for how each person is doing, and a history of their progress. 
        </p>
        <p>
            Due to confidentiality being a key factor, I have created demo data with 2 logins:
        </p>
        <hr>
        <div>
            Username: user <br>
            Password: 123
        </div>
        <hr>
        <div>
             Username: user2 <br>
            Password: 123
        </div>
        <hr>
    </div>

    
</div>
{% endblock content %}